# This playbook contains common plays that will be run on all nodes.
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Install common dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python-setuptools

# apt full-upgrade
- name: Update all packages to the latest version
  apt:
    upgrade: full

  # aptにはない
  #  - libselinux-python
  #  - libsemanage-python
- name: Install common dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python-setuptools
    - zsh
    - tmux
    - git
    - nmap
    - htop
    - neovim
    - docker
    - docker-compose
    # - lsof
    # - snapd
    # - php
  

- name: install the 'Development tools' package group
  apt:
    name: "build-essential"
    state: present

# - name: github
#   snap:
#     name:
#       - github-desktop
#     channel: beta
#     classic: yes
#   tags: ['desktop']


# - name: install dev package
#   apt: name={{ item }} state=installed
#   with_items:
#    - bzip2-devel
#    - gdbm-devel
#    - libffi-devel
#    - libuuid-devel
#    - ncurses-devel
#    - openssl-devel
#    - readline-devel
#    - sqlite-devel
#    - tk-devel
#    - wget
#    - xz-devel
#    - zlib-devel



# - name: snap enable
#   command: systemctl enable --now snapd.socket
